version: '3'

vars:
    COMPILER: latexmk
    JOBNAME: Assignment 7

tasks:
    cleanup:
        vars:
            FLAGS: -c
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }} -jobname="{{ .JOBNAME }}"

    build:
        dir: ./src/
        deps: [ compile:graphics ]
        vars:
            FLAGS: -pdf
            ENTRYPOINT: main.tex
            
            OUTPUT_DIR: ..
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }}            \
              -jobname="{{ .JOBNAME }}"               \
              -output-directory="./{{ .OUTPUT_DIR }}" \
              {{ .ENTRYPOINT }}
    
    merge:
        vars:
            COMPILER: latexpand
            FLAGS: --keep-comments --verbose
            ENTRYPOINT: main.tex
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }} \
              -output="{{ .JOBNAME }}.tex" \
              {{ .ENTRYPOINT }}

    compile:graphics:
        dir: ./src/
        vars:
            INPUT_DIR: content/figures
            OUTPUT_DIR: content/figures
        deps:
            - task: compile:individual-graphic
              vars: {
                INPUT_DIR:  "{{ .INPUT_DIR }}",
                OUTPUT_DIR: "{{ .OUTPUT_DIR }}",
                FILE:       exercise-15.3-3-step-1.tikz
              }
            - task: compile:individual-graphic
              vars: {
                INPUT_DIR:  "{{ .INPUT_DIR }}",
                OUTPUT_DIR: "{{ .OUTPUT_DIR }}",
                FILE:       exercise-15.3-3-step-2.tikz
              }
            - task: compile:individual-graphic
              vars: {
                INPUT_DIR:  "{{ .INPUT_DIR }}",
                OUTPUT_DIR: "{{ .OUTPUT_DIR }}",
                FILE:       exercise-15.3-3-step-3.tikz
              }
            - task: compile:individual-graphic
              vars: {
                INPUT_DIR:  "{{ .INPUT_DIR }}",
                OUTPUT_DIR: "{{ .OUTPUT_DIR }}",
                FILE:       exercise-15.3-3-step-4.tikz
              }
            - task: compile:individual-graphic
              vars: {
                INPUT_DIR:  "{{ .INPUT_DIR }}",
                OUTPUT_DIR: "{{ .OUTPUT_DIR }}",
                FILE:       exercise-15.3-3-step-5.tikz
              }
            - task: compile:individual-graphic
              vars: {
                INPUT_DIR:  "{{ .INPUT_DIR }}",
                OUTPUT_DIR: "{{ .OUTPUT_DIR }}",
                FILE:       exercise-15.3-3-step-6.tikz
              }
            - task: compile:individual-graphic
              vars: {
                INPUT_DIR:  "{{ .INPUT_DIR }}",
                OUTPUT_DIR: "{{ .OUTPUT_DIR }}",
                FILE:       exercise-15.3-3-step-7.tikz
              }

    compile:individual-graphic:
        internal: true
        dir: ./src/
        requires:
            vars: [INPUT_DIR, OUTPUT_DIR, FILE]
        vars:
            FLAGS: -pdf
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }}              \
                -output-directory="./{{ .OUTPUT_DIR }}" \
                {{ .INPUT_DIR }}/{{ .FILE }}