version: '3'

vars:
    COMPILER: latexmk
    JOBNAME: Example

tasks:
    cleanup:
        vars:
            FLAGS: -c
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }} -jobname="{{ .JOBNAME }}"

    compile:
        vars:
            FLAGS: -pdf
            ENTRYPOINT: main.tex
            
            OUTPUT_DIR: .
        cmds:
            - |
              {{ .COMPILER }} {{ .FLAGS }}          \
              -jobname="{{ .JOBNAME }}"             \
              -output-directory="{{ .OUTPUT_DIR }}" \
              {{ .ENTRYPOINT }}